/* AbstcVideoProcessor.c generated by valac 0.12.0, the Vala compiler
 * generated from AbstcVideoProcessor.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <rraew.h>


#define TYPE_ABSTC_VIDEO_PROCESSOR (abstc_video_processor_get_type ())
#define ABSTC_VIDEO_PROCESSOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ABSTC_VIDEO_PROCESSOR, AbstcVideoProcessor))
#define ABSTC_VIDEO_PROCESSOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ABSTC_VIDEO_PROCESSOR, AbstcVideoProcessorClass))
#define IS_ABSTC_VIDEO_PROCESSOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ABSTC_VIDEO_PROCESSOR))
#define IS_ABSTC_VIDEO_PROCESSOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ABSTC_VIDEO_PROCESSOR))
#define ABSTC_VIDEO_PROCESSOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ABSTC_VIDEO_PROCESSOR, AbstcVideoProcessorClass))

typedef struct _AbstcVideoProcessor AbstcVideoProcessor;
typedef struct _AbstcVideoProcessorClass AbstcVideoProcessorClass;
typedef struct _AbstcVideoProcessorPrivate AbstcVideoProcessorPrivate;

struct _AbstcVideoProcessor {
	GObject parent_instance;
	AbstcVideoProcessorPrivate * priv;
	gint previewer_fd;
	gint aew_fd;
	gchar owner_previewer_fd;
	gchar owner_aew_fd;
};

struct _AbstcVideoProcessorClass {
	GObjectClass parent_class;
	gboolean (*get_video_processor_data) (AbstcVideoProcessor* self, struct rraew_interface* interf);
};


static gpointer abstc_video_processor_parent_class = NULL;
extern gboolean abstc_video_processor_debug;
gboolean abstc_video_processor_debug = FALSE;

GType abstc_video_processor_get_type (void) G_GNUC_CONST;
enum  {
	ABSTC_VIDEO_PROCESSOR_DUMMY_PROPERTY
};
gboolean abstc_video_processor_get_video_processor_data (AbstcVideoProcessor* self, struct rraew_interface* interf);
static gboolean abstc_video_processor_real_get_video_processor_data (AbstcVideoProcessor* self, struct rraew_interface* interf);
AbstcVideoProcessor* abstc_video_processor_construct (GType object_type);
static void abstc_video_processor_finalize (GObject* obj);


static gboolean abstc_video_processor_real_get_video_processor_data (AbstcVideoProcessor* self, struct rraew_interface* interf) {
	g_return_val_if_fail (self != NULL, FALSE);
	g_critical ("Type `%s' does not implement abstract method `abstc_video_processor_get_video_processor_data'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return FALSE;
}


gboolean abstc_video_processor_get_video_processor_data (AbstcVideoProcessor* self, struct rraew_interface* interf) {
	return ABSTC_VIDEO_PROCESSOR_GET_CLASS (self)->get_video_processor_data (self, interf);
}


AbstcVideoProcessor* abstc_video_processor_construct (GType object_type) {
	AbstcVideoProcessor * self = NULL;
	self = (AbstcVideoProcessor*) g_object_new (object_type, NULL);
	return self;
}


static void abstc_video_processor_class_init (AbstcVideoProcessorClass * klass) {
	abstc_video_processor_parent_class = g_type_class_peek_parent (klass);
	ABSTC_VIDEO_PROCESSOR_CLASS (klass)->get_video_processor_data = abstc_video_processor_real_get_video_processor_data;
	G_OBJECT_CLASS (klass)->finalize = abstc_video_processor_finalize;
}


static void abstc_video_processor_instance_init (AbstcVideoProcessor * self) {
}


static void abstc_video_processor_finalize (GObject* obj) {
	AbstcVideoProcessor * self;
	self = ABSTC_VIDEO_PROCESSOR (obj);
	G_OBJECT_CLASS (abstc_video_processor_parent_class)->finalize (obj);
}


GType abstc_video_processor_get_type (void) {
	static volatile gsize abstc_video_processor_type_id__volatile = 0;
	if (g_once_init_enter (&abstc_video_processor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AbstcVideoProcessorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) abstc_video_processor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AbstcVideoProcessor), 0, (GInstanceInitFunc) abstc_video_processor_instance_init, NULL };
		GType abstc_video_processor_type_id;
		abstc_video_processor_type_id = g_type_register_static (G_TYPE_OBJECT, "AbstcVideoProcessor", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&abstc_video_processor_type_id__volatile, abstc_video_processor_type_id);
	}
	return abstc_video_processor_type_id__volatile;
}



