/* AbstcCliRegister.c generated by valac 0.12.0, the Vala compiler
 * generated from AbstcCliRegister.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>


#define TYPE_ABSTC_CLI_REGISTER (abstc_cli_register_get_type ())
#define ABSTC_CLI_REGISTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ABSTC_CLI_REGISTER, AbstcCliRegister))
#define ABSTC_CLI_REGISTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ABSTC_CLI_REGISTER, AbstcCliRegisterClass))
#define IS_ABSTC_CLI_REGISTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ABSTC_CLI_REGISTER))
#define IS_ABSTC_CLI_REGISTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ABSTC_CLI_REGISTER))
#define ABSTC_CLI_REGISTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ABSTC_CLI_REGISTER, AbstcCliRegisterClass))

typedef struct _AbstcCliRegister AbstcCliRegister;
typedef struct _AbstcCliRegisterClass AbstcCliRegisterClass;
typedef struct _AbstcCliRegisterPrivate AbstcCliRegisterPrivate;

#define TYPE_IPIPE_CLI (ipipe_cli_get_type ())
#define IPIPE_CLI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IPIPE_CLI, IpipeCli))
#define IPIPE_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IPIPE_CLI, IpipeCliClass))
#define IS_IPIPE_CLI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IPIPE_CLI))
#define IS_IPIPE_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IPIPE_CLI))
#define IPIPE_CLI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IPIPE_CLI, IpipeCliClass))

typedef struct _IpipeCli IpipeCli;
typedef struct _IpipeCliClass IpipeCliClass;

struct _AbstcCliRegister {
	GObject parent_instance;
	AbstcCliRegisterPrivate * priv;
};

struct _AbstcCliRegisterClass {
	GObjectClass parent_class;
	void (*registration) (AbstcCliRegister* self, IpipeCli* cli, GError** error);
};


static gpointer abstc_cli_register_parent_class = NULL;

GType abstc_cli_register_get_type (void) G_GNUC_CONST;
GType ipipe_cli_get_type (void) G_GNUC_CONST;
enum  {
	ABSTC_CLI_REGISTER_DUMMY_PROPERTY
};
void abstc_cli_register_registration (AbstcCliRegister* self, IpipeCli* cli, GError** error);
static void abstc_cli_register_real_registration (AbstcCliRegister* self, IpipeCli* cli, GError** error);
AbstcCliRegister* abstc_cli_register_construct (GType object_type);


static void abstc_cli_register_real_registration (AbstcCliRegister* self, IpipeCli* cli, GError** error) {
	g_return_if_fail (self != NULL);
	g_critical ("Type `%s' does not implement abstract method `abstc_cli_register_registration'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void abstc_cli_register_registration (AbstcCliRegister* self, IpipeCli* cli, GError** error) {
	ABSTC_CLI_REGISTER_GET_CLASS (self)->registration (self, cli, error);
}


AbstcCliRegister* abstc_cli_register_construct (GType object_type) {
	AbstcCliRegister * self = NULL;
	self = (AbstcCliRegister*) g_object_new (object_type, NULL);
	return self;
}


static void abstc_cli_register_class_init (AbstcCliRegisterClass * klass) {
	abstc_cli_register_parent_class = g_type_class_peek_parent (klass);
	ABSTC_CLI_REGISTER_CLASS (klass)->registration = abstc_cli_register_real_registration;
}


static void abstc_cli_register_instance_init (AbstcCliRegister * self) {
}


GType abstc_cli_register_get_type (void) {
	static volatile gsize abstc_cli_register_type_id__volatile = 0;
	if (g_once_init_enter (&abstc_cli_register_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AbstcCliRegisterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) abstc_cli_register_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AbstcCliRegister), 0, (GInstanceInitFunc) abstc_cli_register_instance_init, NULL };
		GType abstc_cli_register_type_id;
		abstc_cli_register_type_id = g_type_register_static (G_TYPE_OBJECT, "AbstcCliRegister", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&abstc_cli_register_type_id__volatile, abstc_cli_register_type_id);
	}
	return abstc_cli_register_type_id__volatile;
}



