/* cli_dm365ipipe.c generated by valac 0.11.5, the Vala compiler
 * generated from cli_dm365ipipe.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>
#include <stdio.h>


#define TYPE_IDM365IPIPE (idm365ipipe_get_type ())
#define IDM365IPIPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IDM365IPIPE, Idm365ipipe))
#define IS_IDM365IPIPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IDM365IPIPE))
#define IDM365IPIPE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_IDM365IPIPE, Idm365ipipeIface))

typedef struct _Idm365ipipe Idm365ipipe;
typedef struct _Idm365ipipeIface Idm365ipipeIface;

#define TYPE_IDM365IPIPE_PROXY (idm365ipipe_proxy_get_type ())
typedef GDBusProxy Idm365ipipeProxy;
typedef GDBusProxyClass Idm365ipipeProxyClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_ABSTC_CLI_REGISTER (abstc_cli_register_get_type ())
#define ABSTC_CLI_REGISTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ABSTC_CLI_REGISTER, AbstcCliRegister))
#define ABSTC_CLI_REGISTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ABSTC_CLI_REGISTER, AbstcCliRegisterClass))
#define IS_ABSTC_CLI_REGISTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ABSTC_CLI_REGISTER))
#define IS_ABSTC_CLI_REGISTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ABSTC_CLI_REGISTER))
#define ABSTC_CLI_REGISTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ABSTC_CLI_REGISTER, AbstcCliRegisterClass))

typedef struct _AbstcCliRegister AbstcCliRegister;
typedef struct _AbstcCliRegisterClass AbstcCliRegisterClass;
typedef struct _AbstcCliRegisterPrivate AbstcCliRegisterPrivate;

#define TYPE_IPIPE_CLI (ipipe_cli_get_type ())
#define IPIPE_CLI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IPIPE_CLI, IpipeCli))
#define IPIPE_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IPIPE_CLI, IpipeCliClass))
#define IS_IPIPE_CLI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IPIPE_CLI))
#define IS_IPIPE_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IPIPE_CLI))
#define IPIPE_CLI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IPIPE_CLI, IpipeCliClass))

typedef struct _IpipeCli IpipeCli;
typedef struct _IpipeCliClass IpipeCliClass;

#define TYPE_CLI_DM365IPIPE (cli_dm365ipipe_get_type ())
#define CLI_DM365IPIPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CLI_DM365IPIPE, cli_dm365ipipe))
#define CLI_DM365IPIPE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CLI_DM365IPIPE, cli_dm365ipipeClass))
#define IS_CLI_DM365IPIPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CLI_DM365IPIPE))
#define IS_CLI_DM365IPIPE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CLI_DM365IPIPE))
#define CLI_DM365IPIPE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CLI_DM365IPIPE, cli_dm365ipipeClass))

typedef struct _cli_dm365ipipe cli_dm365ipipe;
typedef struct _cli_dm365ipipeClass cli_dm365ipipeClass;
typedef struct _cli_dm365ipipePrivate cli_dm365ipipePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _IpipeCliPrivate IpipeCliPrivate;

#define TYPE_COMMAND_MANAGER (command_manager_get_type ())
#define COMMAND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMMAND_MANAGER, CommandManager))
#define COMMAND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMMAND_MANAGER, CommandManagerClass))
#define IS_COMMAND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMMAND_MANAGER))
#define IS_COMMAND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMMAND_MANAGER))
#define COMMAND_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMMAND_MANAGER, CommandManagerClass))

typedef struct _CommandManager CommandManager;
typedef struct _CommandManagerClass CommandManagerClass;

struct _Idm365ipipeIface {
	GTypeInterface parent_iface;
	gint (*ping2) (Idm365ipipe* self, const gchar* msg, GError** error);
	gboolean (*set_previewer_mode) (Idm365ipipe* self, const gchar* mode_s, GError** error);
	gint (*set_color_pattern) (Idm365ipipe* self, const gchar* colorptn, GError** error);
	gint (*set_digital_gain) (Idm365ipipe* self, gdouble _red_gain, gdouble _green_gain, gdouble _blue_gain, GError** error);
	gint (*get_digital_gain) (Idm365ipipe* self, GError** error);
	gint (*set_luminance_adj) (Idm365ipipe* self, gint bright, gdouble contr, GError** error);
	gint (*get_luminance_adj) (Idm365ipipe* self, GError** error);
};

struct _AbstcCliRegister {
	GObject parent_instance;
	AbstcCliRegisterPrivate * priv;
};

struct _AbstcCliRegisterClass {
	GObjectClass parent_class;
	void (*registration) (AbstcCliRegister* self, IpipeCli* cli, GError** error);
};

struct _cli_dm365ipipe {
	AbstcCliRegister parent_instance;
	cli_dm365ipipePrivate * priv;
	Idm365ipipe* ipipe;
};

struct _cli_dm365ipipeClass {
	AbstcCliRegisterClass parent_class;
};

struct _IpipeCli {
	GObject parent_instance;
	IpipeCliPrivate * priv;
	CommandManager* cmd;
};

struct _IpipeCliClass {
	GObjectClass parent_class;
};

typedef gint (*IpipeCommandCmdFunc) (gchar** s, int s_length1, void* user_data);

static gpointer cli_dm365ipipe_parent_class = NULL;
static gboolean cli_dm365ipipe__debug;
static gboolean cli_dm365ipipe__debug = FALSE;

GType idm365ipipe_proxy_get_type (void) G_GNUC_CONST;
guint idm365ipipe_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType idm365ipipe_get_type (void) G_GNUC_CONST;
gint idm365ipipe_ping2 (Idm365ipipe* self, const gchar* msg, GError** error);
gboolean idm365ipipe_set_previewer_mode (Idm365ipipe* self, const gchar* mode_s, GError** error);
gint idm365ipipe_set_color_pattern (Idm365ipipe* self, const gchar* colorptn, GError** error);
gint idm365ipipe_set_digital_gain (Idm365ipipe* self, gdouble _red_gain, gdouble _green_gain, gdouble _blue_gain, GError** error);
gint idm365ipipe_get_digital_gain (Idm365ipipe* self, GError** error);
gint idm365ipipe_set_luminance_adj (Idm365ipipe* self, gint bright, gdouble contr, GError** error);
gint idm365ipipe_get_luminance_adj (Idm365ipipe* self, GError** error);
static void idm365ipipe_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static gint idm365ipipe_proxy_ping2 (Idm365ipipe* self, const gchar* msg, GError** error);
static gboolean idm365ipipe_proxy_set_previewer_mode (Idm365ipipe* self, const gchar* mode_s, GError** error);
static gint idm365ipipe_proxy_set_color_pattern (Idm365ipipe* self, const gchar* colorptn, GError** error);
static gint idm365ipipe_proxy_set_digital_gain (Idm365ipipe* self, gdouble _red_gain, gdouble _green_gain, gdouble _blue_gain, GError** error);
static gint idm365ipipe_proxy_get_digital_gain (Idm365ipipe* self, GError** error);
static gint idm365ipipe_proxy_set_luminance_adj (Idm365ipipe* self, gint bright, gdouble contr, GError** error);
static gint idm365ipipe_proxy_get_luminance_adj (Idm365ipipe* self, GError** error);
static void idm365ipipe_proxy_idm365ipipe_interface_init (Idm365ipipeIface* iface);
static void _dbus_idm365ipipe_ping2 (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_idm365ipipe_set_previewer_mode (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_idm365ipipe_set_color_pattern (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_idm365ipipe_set_digital_gain (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_idm365ipipe_get_digital_gain (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_idm365ipipe_set_luminance_adj (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_idm365ipipe_get_luminance_adj (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void idm365ipipe_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* idm365ipipe_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean idm365ipipe_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _idm365ipipe_unregister_object (gpointer user_data);
GType abstc_cli_register_get_type (void) G_GNUC_CONST;
GType ipipe_cli_get_type (void) G_GNUC_CONST;
GType cli_dm365ipipe_get_type (void) G_GNUC_CONST;
enum  {
	CLI_DM365IPIPE_DUMMY_PROPERTY
};
cli_dm365ipipe* cli_dm365ipipe_new (gboolean debug, GError** error);
cli_dm365ipipe* cli_dm365ipipe_construct (GType object_type, gboolean debug, GError** error);
AbstcCliRegister* abstc_cli_register_construct (GType object_type);
static gint cli_dm365ipipe_cmd_set_previewer_mode (cli_dm365ipipe* self, gchar** args, int args_length1);
static gint cli_dm365ipipe_cmd_set_digital_gain (cli_dm365ipipe* self, gchar** args, int args_length1);
static gint cli_dm365ipipe_cmd_get_digital_gain (cli_dm365ipipe* self, gchar** args, int args_length1);
static gint cli_dm365ipipe_cmd_set_lum_adj (cli_dm365ipipe* self, gchar** args, int args_length1);
static gint cli_dm365ipipe_cmd_get_lum_adj (cli_dm365ipipe* self, gchar** args, int args_length1);
static gint cli_dm365ipipe_cmd_set_color_pattern (cli_dm365ipipe* self, gchar** args, int args_length1);
static void cli_dm365ipipe_real_registration (AbstcCliRegister* base, IpipeCli* cli, GError** error);
GType command_manager_get_type (void) G_GNUC_CONST;
void command_manager_new_command (CommandManager* self, const gchar* _name, IpipeCommandCmdFunc _cmdfunc, void* _cmdfunc_target, const gchar* _usage, const gchar* _doc, const gchar* _args);
static gint _cli_dm365ipipe_cmd_set_previewer_mode_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_dm365ipipe_cmd_set_color_pattern_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_dm365ipipe_cmd_set_digital_gain_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_dm365ipipe_cmd_get_digital_gain_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_dm365ipipe_cmd_set_lum_adj_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_dm365ipipe_cmd_get_lum_adj_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static void cli_dm365ipipe_finalize (GObject* obj);

static const GDBusArgInfo _idm365ipipe_dbus_arg_info_ping2_msg = {-1, "msg", "s"};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_ping2_result = {-1, "result", "i"};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_ping2_in[] = {&_idm365ipipe_dbus_arg_info_ping2_msg, NULL};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_ping2_out[] = {&_idm365ipipe_dbus_arg_info_ping2_result, NULL};
static const GDBusMethodInfo _idm365ipipe_dbus_method_info_ping2 = {-1, "Ping2", (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_ping2_in), (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_ping2_out)};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_previewer_mode_mode_s = {-1, "mode_s", "s"};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_previewer_mode_result = {-1, "result", "b"};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_set_previewer_mode_in[] = {&_idm365ipipe_dbus_arg_info_set_previewer_mode_mode_s, NULL};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_set_previewer_mode_out[] = {&_idm365ipipe_dbus_arg_info_set_previewer_mode_result, NULL};
static const GDBusMethodInfo _idm365ipipe_dbus_method_info_set_previewer_mode = {-1, "SetPreviewerMode", (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_set_previewer_mode_in), (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_set_previewer_mode_out)};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_color_pattern_colorptn = {-1, "colorptn", "s"};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_color_pattern_result = {-1, "result", "i"};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_set_color_pattern_in[] = {&_idm365ipipe_dbus_arg_info_set_color_pattern_colorptn, NULL};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_set_color_pattern_out[] = {&_idm365ipipe_dbus_arg_info_set_color_pattern_result, NULL};
static const GDBusMethodInfo _idm365ipipe_dbus_method_info_set_color_pattern = {-1, "SetColorPattern", (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_set_color_pattern_in), (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_set_color_pattern_out)};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_digital_gain__red_gain = {-1, "_red_gain", "d"};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_digital_gain__green_gain = {-1, "_green_gain", "d"};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_digital_gain__blue_gain = {-1, "_blue_gain", "d"};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_digital_gain_result = {-1, "result", "i"};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_set_digital_gain_in[] = {&_idm365ipipe_dbus_arg_info_set_digital_gain__red_gain, &_idm365ipipe_dbus_arg_info_set_digital_gain__green_gain, &_idm365ipipe_dbus_arg_info_set_digital_gain__blue_gain, NULL};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_set_digital_gain_out[] = {&_idm365ipipe_dbus_arg_info_set_digital_gain_result, NULL};
static const GDBusMethodInfo _idm365ipipe_dbus_method_info_set_digital_gain = {-1, "SetDigitalGain", (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_set_digital_gain_in), (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_set_digital_gain_out)};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_get_digital_gain_result = {-1, "result", "i"};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_get_digital_gain_in[] = {NULL};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_get_digital_gain_out[] = {&_idm365ipipe_dbus_arg_info_get_digital_gain_result, NULL};
static const GDBusMethodInfo _idm365ipipe_dbus_method_info_get_digital_gain = {-1, "GetDigitalGain", (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_get_digital_gain_in), (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_get_digital_gain_out)};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_luminance_adj_bright = {-1, "bright", "i"};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_luminance_adj_contr = {-1, "contr", "d"};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_set_luminance_adj_result = {-1, "result", "i"};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_set_luminance_adj_in[] = {&_idm365ipipe_dbus_arg_info_set_luminance_adj_bright, &_idm365ipipe_dbus_arg_info_set_luminance_adj_contr, NULL};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_set_luminance_adj_out[] = {&_idm365ipipe_dbus_arg_info_set_luminance_adj_result, NULL};
static const GDBusMethodInfo _idm365ipipe_dbus_method_info_set_luminance_adj = {-1, "SetLuminanceAdj", (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_set_luminance_adj_in), (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_set_luminance_adj_out)};
static const GDBusArgInfo _idm365ipipe_dbus_arg_info_get_luminance_adj_result = {-1, "result", "i"};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_get_luminance_adj_in[] = {NULL};
static const GDBusArgInfo * const _idm365ipipe_dbus_arg_info_get_luminance_adj_out[] = {&_idm365ipipe_dbus_arg_info_get_luminance_adj_result, NULL};
static const GDBusMethodInfo _idm365ipipe_dbus_method_info_get_luminance_adj = {-1, "GetLuminanceAdj", (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_get_luminance_adj_in), (GDBusArgInfo **) (&_idm365ipipe_dbus_arg_info_get_luminance_adj_out)};
static const GDBusMethodInfo * const _idm365ipipe_dbus_method_info[] = {&_idm365ipipe_dbus_method_info_ping2, &_idm365ipipe_dbus_method_info_set_previewer_mode, &_idm365ipipe_dbus_method_info_set_color_pattern, &_idm365ipipe_dbus_method_info_set_digital_gain, &_idm365ipipe_dbus_method_info_get_digital_gain, &_idm365ipipe_dbus_method_info_set_luminance_adj, &_idm365ipipe_dbus_method_info_get_luminance_adj, NULL};
static const GDBusSignalInfo * const _idm365ipipe_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _idm365ipipe_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _idm365ipipe_dbus_interface_info = {-1, "com.ridgerun.dm365ipipeInterface", (GDBusMethodInfo **) (&_idm365ipipe_dbus_method_info), (GDBusSignalInfo **) (&_idm365ipipe_dbus_signal_info), (GDBusPropertyInfo **) (&_idm365ipipe_dbus_property_info)};
static const GDBusInterfaceVTable _idm365ipipe_dbus_interface_vtable = {idm365ipipe_dbus_interface_method_call, idm365ipipe_dbus_interface_get_property, idm365ipipe_dbus_interface_set_property};

gint idm365ipipe_ping2 (Idm365ipipe* self, const gchar* msg, GError** error) {
	return IDM365IPIPE_GET_INTERFACE (self)->ping2 (self, msg, error);
}


gboolean idm365ipipe_set_previewer_mode (Idm365ipipe* self, const gchar* mode_s, GError** error) {
	return IDM365IPIPE_GET_INTERFACE (self)->set_previewer_mode (self, mode_s, error);
}


gint idm365ipipe_set_color_pattern (Idm365ipipe* self, const gchar* colorptn, GError** error) {
	return IDM365IPIPE_GET_INTERFACE (self)->set_color_pattern (self, colorptn, error);
}


gint idm365ipipe_set_digital_gain (Idm365ipipe* self, gdouble _red_gain, gdouble _green_gain, gdouble _blue_gain, GError** error) {
	return IDM365IPIPE_GET_INTERFACE (self)->set_digital_gain (self, _red_gain, _green_gain, _blue_gain, error);
}


gint idm365ipipe_get_digital_gain (Idm365ipipe* self, GError** error) {
	return IDM365IPIPE_GET_INTERFACE (self)->get_digital_gain (self, error);
}


gint idm365ipipe_set_luminance_adj (Idm365ipipe* self, gint bright, gdouble contr, GError** error) {
	return IDM365IPIPE_GET_INTERFACE (self)->set_luminance_adj (self, bright, contr, error);
}


gint idm365ipipe_get_luminance_adj (Idm365ipipe* self, GError** error) {
	return IDM365IPIPE_GET_INTERFACE (self)->get_luminance_adj (self, error);
}


static void idm365ipipe_base_init (Idm365ipipeIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType idm365ipipe_get_type (void) {
	static volatile gsize idm365ipipe_type_id__volatile = 0;
	if (g_once_init_enter (&idm365ipipe_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Idm365ipipeIface), (GBaseInitFunc) idm365ipipe_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType idm365ipipe_type_id;
		idm365ipipe_type_id = g_type_register_static (G_TYPE_INTERFACE, "Idm365ipipe", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (idm365ipipe_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (idm365ipipe_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) idm365ipipe_proxy_get_type);
		g_type_set_qdata (idm365ipipe_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "com.ridgerun.dm365ipipeInterface");
		g_type_set_qdata (idm365ipipe_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) idm365ipipe_register_object);
		g_once_init_leave (&idm365ipipe_type_id__volatile, idm365ipipe_type_id);
	}
	return idm365ipipe_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (Idm365ipipeProxy, idm365ipipe_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_IDM365IPIPE, idm365ipipe_proxy_idm365ipipe_interface_init) );
static void idm365ipipe_proxy_class_init (Idm365ipipeProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = idm365ipipe_proxy_g_signal;
}


static void idm365ipipe_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void idm365ipipe_proxy_init (Idm365ipipeProxy* self) {
}


static gint idm365ipipe_proxy_ping2 (Idm365ipipe* self, const gchar* msg, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp14_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.dm365ipipeInterface", "Ping2");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (msg));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp14_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp14_);
	g_variant_unref (_tmp14_);
	g_object_unref (_reply_message);
	return _result;
}


static gboolean idm365ipipe_proxy_set_previewer_mode (Idm365ipipe* self, const gchar* mode_s, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gboolean _result;
	GVariant* _tmp15_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.dm365ipipeInterface", "SetPreviewerMode");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (mode_s));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return FALSE;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return FALSE;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp15_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_boolean (_tmp15_);
	g_variant_unref (_tmp15_);
	g_object_unref (_reply_message);
	return _result;
}


static gint idm365ipipe_proxy_set_color_pattern (Idm365ipipe* self, const gchar* colorptn, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp16_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.dm365ipipeInterface", "SetColorPattern");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (colorptn));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp16_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp16_);
	g_variant_unref (_tmp16_);
	g_object_unref (_reply_message);
	return _result;
}


static gint idm365ipipe_proxy_set_digital_gain (Idm365ipipe* self, gdouble _red_gain, gdouble _green_gain, gdouble _blue_gain, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp17_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.dm365ipipeInterface", "SetDigitalGain");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (_red_gain));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (_green_gain));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (_blue_gain));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp17_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp17_);
	g_variant_unref (_tmp17_);
	g_object_unref (_reply_message);
	return _result;
}


static gint idm365ipipe_proxy_get_digital_gain (Idm365ipipe* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp18_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.dm365ipipeInterface", "GetDigitalGain");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp18_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp18_);
	g_variant_unref (_tmp18_);
	g_object_unref (_reply_message);
	return _result;
}


static gint idm365ipipe_proxy_set_luminance_adj (Idm365ipipe* self, gint bright, gdouble contr, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp19_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.dm365ipipeInterface", "SetLuminanceAdj");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (bright));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (contr));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp19_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp19_);
	g_variant_unref (_tmp19_);
	g_object_unref (_reply_message);
	return _result;
}


static gint idm365ipipe_proxy_get_luminance_adj (Idm365ipipe* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp20_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.dm365ipipeInterface", "GetLuminanceAdj");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp20_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp20_);
	g_variant_unref (_tmp20_);
	g_object_unref (_reply_message);
	return _result;
}


static void idm365ipipe_proxy_idm365ipipe_interface_init (Idm365ipipeIface* iface) {
	iface->ping2 = idm365ipipe_proxy_ping2;
	iface->set_previewer_mode = idm365ipipe_proxy_set_previewer_mode;
	iface->set_color_pattern = idm365ipipe_proxy_set_color_pattern;
	iface->set_digital_gain = idm365ipipe_proxy_set_digital_gain;
	iface->get_digital_gain = idm365ipipe_proxy_get_digital_gain;
	iface->set_luminance_adj = idm365ipipe_proxy_set_luminance_adj;
	iface->get_luminance_adj = idm365ipipe_proxy_get_luminance_adj;
}


static void _dbus_idm365ipipe_ping2 (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* msg = NULL;
	GVariant* _tmp21_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp21_ = g_variant_iter_next_value (&_arguments_iter);
	msg = g_variant_dup_string (_tmp21_, NULL);
	g_variant_unref (_tmp21_);
	result = idm365ipipe_ping2 (self, msg, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (msg);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_idm365ipipe_set_previewer_mode (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* mode_s = NULL;
	GVariant* _tmp22_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gboolean result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp22_ = g_variant_iter_next_value (&_arguments_iter);
	mode_s = g_variant_dup_string (_tmp22_, NULL);
	g_variant_unref (_tmp22_);
	result = idm365ipipe_set_previewer_mode (self, mode_s, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_boolean (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (mode_s);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_idm365ipipe_set_color_pattern (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* colorptn = NULL;
	GVariant* _tmp23_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp23_ = g_variant_iter_next_value (&_arguments_iter);
	colorptn = g_variant_dup_string (_tmp23_, NULL);
	g_variant_unref (_tmp23_);
	result = idm365ipipe_set_color_pattern (self, colorptn, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (colorptn);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_idm365ipipe_set_digital_gain (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gdouble _red_gain = 0.0;
	GVariant* _tmp24_;
	gdouble _green_gain = 0.0;
	GVariant* _tmp25_;
	gdouble _blue_gain = 0.0;
	GVariant* _tmp26_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp24_ = g_variant_iter_next_value (&_arguments_iter);
	_red_gain = g_variant_get_double (_tmp24_);
	g_variant_unref (_tmp24_);
	_tmp25_ = g_variant_iter_next_value (&_arguments_iter);
	_green_gain = g_variant_get_double (_tmp25_);
	g_variant_unref (_tmp25_);
	_tmp26_ = g_variant_iter_next_value (&_arguments_iter);
	_blue_gain = g_variant_get_double (_tmp26_);
	g_variant_unref (_tmp26_);
	result = idm365ipipe_set_digital_gain (self, _red_gain, _green_gain, _blue_gain, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_idm365ipipe_get_digital_gain (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = idm365ipipe_get_digital_gain (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_idm365ipipe_set_luminance_adj (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gint bright = 0;
	GVariant* _tmp27_;
	gdouble contr = 0.0;
	GVariant* _tmp28_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp27_ = g_variant_iter_next_value (&_arguments_iter);
	bright = g_variant_get_int32 (_tmp27_);
	g_variant_unref (_tmp27_);
	_tmp28_ = g_variant_iter_next_value (&_arguments_iter);
	contr = g_variant_get_double (_tmp28_);
	g_variant_unref (_tmp28_);
	result = idm365ipipe_set_luminance_adj (self, bright, contr, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_idm365ipipe_get_luminance_adj (Idm365ipipe* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = idm365ipipe_get_luminance_adj (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void idm365ipipe_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "Ping2") == 0) {
		_dbus_idm365ipipe_ping2 (object, parameters, invocation);
	} else if (strcmp (method_name, "SetPreviewerMode") == 0) {
		_dbus_idm365ipipe_set_previewer_mode (object, parameters, invocation);
	} else if (strcmp (method_name, "SetColorPattern") == 0) {
		_dbus_idm365ipipe_set_color_pattern (object, parameters, invocation);
	} else if (strcmp (method_name, "SetDigitalGain") == 0) {
		_dbus_idm365ipipe_set_digital_gain (object, parameters, invocation);
	} else if (strcmp (method_name, "GetDigitalGain") == 0) {
		_dbus_idm365ipipe_get_digital_gain (object, parameters, invocation);
	} else if (strcmp (method_name, "SetLuminanceAdj") == 0) {
		_dbus_idm365ipipe_set_luminance_adj (object, parameters, invocation);
	} else if (strcmp (method_name, "GetLuminanceAdj") == 0) {
		_dbus_idm365ipipe_get_luminance_adj (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* idm365ipipe_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean idm365ipipe_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint idm365ipipe_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_idm365ipipe_dbus_interface_info), &_idm365ipipe_dbus_interface_vtable, data, _idm365ipipe_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _idm365ipipe_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


cli_dm365ipipe* cli_dm365ipipe_construct (GType object_type, gboolean debug, GError** error) {
	cli_dm365ipipe * self = NULL;
	self = (cli_dm365ipipe*) abstc_cli_register_construct (object_type);
	cli_dm365ipipe__debug = debug;
	return self;
}


cli_dm365ipipe* cli_dm365ipipe_new (gboolean debug, GError** error) {
	return cli_dm365ipipe_construct (TYPE_CLI_DM365IPIPE, debug, error);
}


static gint cli_dm365ipipe_cmd_set_previewer_mode (cli_dm365ipipe* self, gchar** args, int args_length1) {
	gint result = 0;
	gboolean _tmp0_;
	gboolean ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	if (args[1] == NULL) {
		fprintf (stdout, "Error:\nMissing argument.Execute:'help <command>'\n");
		result = -1;
		return result;
	}
	_tmp0_ = idm365ipipe_set_previewer_mode (self->ipipe, args[1], &_inner_error_);
	ret = _tmp0_;
	if (_inner_error_ != NULL) {
		goto __catch9_g_error;
	}
	if (!ret) {
		fprintf (stderr, "Error:\n Failed to configure previewer\n");
		result = -1;
		return result;
	} else {
		if (cli_dm365ipipe__debug) {
			fprintf (stdout, "Ipipe Previewer has been configured\n");
			fprintf (stdout, "Ok.\n");
		}
		result = 0;
		return result;
	}
	goto __finally9;
	__catch9_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally9:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


static gint cli_dm365ipipe_cmd_set_digital_gain (cli_dm365ipipe* self, gchar** args, int args_length1) {
	gint result = 0;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gdouble _tmp2_;
	gdouble red;
	gdouble _tmp3_;
	gdouble green;
	gdouble _tmp4_;
	gdouble blue;
	gint _tmp5_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	if (args[1] == NULL) {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = args[2] == NULL;
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = args[3] == NULL;
	}
	if (_tmp0_) {
		fprintf (stdout, "Error:\nMissing argument.Execute:'help <command>'\n");
		result = -1;
		return result;
	}
	_tmp2_ = g_ascii_strtod (args[1], NULL);
	red = _tmp2_;
	_tmp3_ = g_ascii_strtod (args[2], NULL);
	green = _tmp3_;
	_tmp4_ = g_ascii_strtod (args[3], NULL);
	blue = _tmp4_;
	_tmp5_ = idm365ipipe_set_digital_gain (self->ipipe, red, green, blue, &_inner_error_);
	ret = _tmp5_;
	if (_inner_error_ != NULL) {
		goto __catch10_g_error;
	}
	if (ret < 0) {
		fprintf (stderr, "Error:\n Failed to set the digital gain\n");
		result = -1;
		return result;
	} else {
		if (cli_dm365ipipe__debug) {
			fprintf (stdout, "Ok.Set digital gain\n");
		}
		result = 0;
		return result;
	}
	goto __finally10;
	__catch10_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally10:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


static gint cli_dm365ipipe_cmd_get_digital_gain (cli_dm365ipipe* self, gchar** args, int args_length1) {
	gint result = 0;
	gint _tmp0_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = idm365ipipe_get_digital_gain (self->ipipe, &_inner_error_);
	ret = _tmp0_;
	if (_inner_error_ != NULL) {
		goto __catch11_g_error;
	}
	if (ret < 0) {
		fprintf (stderr, "Error:\n Failed to set the digital gain\n");
		result = -1;
		return result;
	} else {
		if (cli_dm365ipipe__debug) {
			fprintf (stdout, "Ok.Get digital gain\n");
		}
		result = 0;
		return result;
	}
	goto __finally11;
	__catch11_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally11:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


static gint cli_dm365ipipe_cmd_set_lum_adj (cli_dm365ipipe* self, gchar** args, int args_length1) {
	gint result = 0;
	gboolean _tmp0_ = FALSE;
	gint _tmp1_;
	gint brightness;
	gdouble _tmp2_;
	gdouble contrast;
	gint _tmp3_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	if (args[1] == NULL) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = args[2] == NULL;
	}
	if (_tmp0_) {
		fprintf (stdout, "Error:\nMissing argument.Execute:'help <command>'\n");
		result = -1;
		return result;
	}
	_tmp1_ = atoi (args[1]);
	brightness = _tmp1_;
	_tmp2_ = g_ascii_strtod (args[2], NULL);
	contrast = _tmp2_;
	_tmp3_ = idm365ipipe_set_luminance_adj (self->ipipe, brightness, contrast, &_inner_error_);
	ret = _tmp3_;
	if (_inner_error_ != NULL) {
		goto __catch12_g_error;
	}
	if (ret < 0) {
		fprintf (stderr, "Error:\n Failed to set the luminant adjusment\n");
		result = -1;
		return result;
	} else {
		if (cli_dm365ipipe__debug) {
			fprintf (stdout, "Ok.Set luminance adjusment\n");
		}
		result = 0;
		return result;
	}
	goto __finally12;
	__catch12_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally12:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


static gint cli_dm365ipipe_cmd_get_lum_adj (cli_dm365ipipe* self, gchar** args, int args_length1) {
	gint result = 0;
	gint _tmp0_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = idm365ipipe_get_luminance_adj (self->ipipe, &_inner_error_);
	ret = _tmp0_;
	if (_inner_error_ != NULL) {
		goto __catch13_g_error;
	}
	if (ret < 0) {
		fprintf (stderr, "Error:\n Failed to get the luminant adjusment\n");
		result = -1;
		return result;
	} else {
		if (cli_dm365ipipe__debug) {
			fprintf (stdout, "Ok.Get luminance adjusment\n");
		}
		result = 0;
		return result;
	}
	goto __finally13;
	__catch13_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally13:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


static gint cli_dm365ipipe_cmd_set_color_pattern (cli_dm365ipipe* self, gchar** args, int args_length1) {
	gint result = 0;
	gint _tmp0_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	if (args[1] == NULL) {
		fprintf (stdout, "Error:\nMissing argument.Execute:'help <command>'\n");
		result = -1;
		return result;
	}
	_tmp0_ = idm365ipipe_set_color_pattern (self->ipipe, args[1], &_inner_error_);
	ret = _tmp0_;
	if (_inner_error_ != NULL) {
		goto __catch14_g_error;
	}
	if (ret != 0) {
		fprintf (stderr, "Error:\n Failed to set color_pattern\n");
		result = -1;
		return result;
	} else {
		if (cli_dm365ipipe__debug) {
			fprintf (stdout, "Ok.Set bayer pattern\n");
		}
		result = 0;
		return result;
	}
	goto __finally14;
	__catch14_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally14:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


static gint _cli_dm365ipipe_cmd_set_previewer_mode_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_dm365ipipe_cmd_set_previewer_mode (self, s, s_length1);
	return result;
}


static gint _cli_dm365ipipe_cmd_set_color_pattern_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_dm365ipipe_cmd_set_color_pattern (self, s, s_length1);
	return result;
}


static gint _cli_dm365ipipe_cmd_set_digital_gain_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_dm365ipipe_cmd_set_digital_gain (self, s, s_length1);
	return result;
}


static gint _cli_dm365ipipe_cmd_get_digital_gain_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_dm365ipipe_cmd_get_digital_gain (self, s, s_length1);
	return result;
}


static gint _cli_dm365ipipe_cmd_set_lum_adj_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_dm365ipipe_cmd_set_lum_adj (self, s, s_length1);
	return result;
}


static gint _cli_dm365ipipe_cmd_get_lum_adj_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_dm365ipipe_cmd_get_lum_adj (self, s, s_length1);
	return result;
}


static void cli_dm365ipipe_real_registration (AbstcCliRegister* base, IpipeCli* cli, GError** error) {
	cli_dm365ipipe * self;
	Idm365ipipe* _tmp0_ = NULL;
	Idm365ipipe* _tmp1_;
	Idm365ipipe* _tmp2_;
	GError * _inner_error_ = NULL;
	self = (cli_dm365ipipe*) base;
	g_return_if_fail (cli != NULL);
	command_manager_new_command (cli->cmd, "set-previewer-mode", _cli_dm365ipipe_cmd_set_previewer_mode_ipipe_command_cmd_func, self, "set_previewer_mode <cont/one-shot>", "Configure previewer on " "continuous or one-shot mode", "\n\tcont: sets previewer on " "continous mode\n\tone-shot: sets previewer on one shot mode");
	command_manager_new_command (cli->cmd, "set-bayer-pattern", _cli_dm365ipipe_cmd_set_color_pattern_ipipe_command_cmd_func, self, "set-bayer-pattern <ptrn>", "Sets R/Gr/Gb/B color pattern to the " "previewer", "\n\tThe argument ptrn is the specific color " "pattern, \n\t\tthe options are: " "\n\tGrRBGb: \n\t\tGr R\n\t\tB Gb\n\tBGbGrR: \n\t\tB Gb\n\t\tGr R" "\n\tRGrGbB: \n\t\tR Gr\n\t\tGb B\n\tGbBRGr: \n\t\tGb B\n\t\tR Gr");
	command_manager_new_command (cli->cmd, "set-digital-gain", _cli_dm365ipipe_cmd_set_digital_gain_ipipe_command_cmd_func, self, "set-digital-gain <R> <G> <B>", "Sets red (R), green (G) and blue" " gains (G) on the ipipe", "\n" \
"\tEach gain component can range from 0 to 15.998 in steps of 1/512:" "\n\tR: red gain\n\tG: green gain\n\tB: blue gain\n");
	command_manager_new_command (cli->cmd, "get-digital-gain", _cli_dm365ipipe_cmd_get_digital_gain_ipipe_command_cmd_func, self, "get-digital-gain", "Returns the gain value for each color component(RGB)", "");
	command_manager_new_command (cli->cmd, "set-luminance", _cli_dm365ipipe_cmd_set_lum_adj_ipipe_command_cmd_func, self, "set-luminance <Br> <C>", "Brightness(Br) and contrast(C) adjustment", "\n\tThis ajustment" "is applied to the luminance(Y) component, using the following " "equation  Yctr_ brt = (Y x C) + Br " "\n\tBr: brightness offset value for ipipe's brightness control," " it's an integer value that can range from 0 to 255" "\n\tCr: contrast multiplier coefficient, it's a float value" " that can range from 0 to 15.94");
	command_manager_new_command (cli->cmd, "get-luminance", _cli_dm365ipipe_cmd_get_lum_adj_ipipe_command_cmd_func, self, "get-luminance", "Returns the value of the Brightness(Br) and contrast(C) adjustment", "");
	_tmp0_ = g_initable_new (TYPE_IDM365IPIPE_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "com.ridgerun.ipiped", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", "/com/ridgerun/ipiped/ipipe", "g-interface-name", "com.ridgerun.dm365ipipeInterface", NULL);
	_tmp1_ = (Idm365ipipe*) _tmp0_;
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_IO_ERROR) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_tmp2_ = _tmp1_;
	_g_object_unref0 (self->ipipe);
	self->ipipe = _tmp2_;
	return;
}


static void cli_dm365ipipe_class_init (cli_dm365ipipeClass * klass) {
	cli_dm365ipipe_parent_class = g_type_class_peek_parent (klass);
	ABSTC_CLI_REGISTER_CLASS (klass)->registration = cli_dm365ipipe_real_registration;
	G_OBJECT_CLASS (klass)->finalize = cli_dm365ipipe_finalize;
}


static void cli_dm365ipipe_instance_init (cli_dm365ipipe * self) {
}


static void cli_dm365ipipe_finalize (GObject* obj) {
	cli_dm365ipipe * self;
	self = CLI_DM365IPIPE (obj);
	_g_object_unref0 (self->ipipe);
	G_OBJECT_CLASS (cli_dm365ipipe_parent_class)->finalize (obj);
}


GType cli_dm365ipipe_get_type (void) {
	static volatile gsize cli_dm365ipipe_type_id__volatile = 0;
	if (g_once_init_enter (&cli_dm365ipipe_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (cli_dm365ipipeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cli_dm365ipipe_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (cli_dm365ipipe), 0, (GInstanceInitFunc) cli_dm365ipipe_instance_init, NULL };
		GType cli_dm365ipipe_type_id;
		cli_dm365ipipe_type_id = g_type_register_static (TYPE_ABSTC_CLI_REGISTER, "cli_dm365ipipe", &g_define_type_info, 0);
		g_once_init_leave (&cli_dm365ipipe_type_id__volatile, cli_dm365ipipe_type_id);
	}
	return cli_dm365ipipe_type_id__volatile;
}



