/* cli_mt9p031.c generated by valac 0.12.0, the Vala compiler
 * generated from cli_mt9p031.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_IMT9P031 (imt9p031_get_type ())
#define IMT9P031(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IMT9P031, Imt9p031))
#define IS_IMT9P031(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IMT9P031))
#define IMT9P031_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_IMT9P031, Imt9p031Iface))

typedef struct _Imt9p031 Imt9p031;
typedef struct _Imt9p031Iface Imt9p031Iface;

#define TYPE_IMT9P031_PROXY (imt9p031_proxy_get_type ())
typedef GDBusProxy Imt9p031Proxy;
typedef GDBusProxyClass Imt9p031ProxyClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_ABSTC_CLI_REGISTER (abstc_cli_register_get_type ())
#define ABSTC_CLI_REGISTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ABSTC_CLI_REGISTER, AbstcCliRegister))
#define ABSTC_CLI_REGISTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ABSTC_CLI_REGISTER, AbstcCliRegisterClass))
#define IS_ABSTC_CLI_REGISTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ABSTC_CLI_REGISTER))
#define IS_ABSTC_CLI_REGISTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ABSTC_CLI_REGISTER))
#define ABSTC_CLI_REGISTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ABSTC_CLI_REGISTER, AbstcCliRegisterClass))

typedef struct _AbstcCliRegister AbstcCliRegister;
typedef struct _AbstcCliRegisterClass AbstcCliRegisterClass;
typedef struct _AbstcCliRegisterPrivate AbstcCliRegisterPrivate;

#define TYPE_IPIPE_CLI (ipipe_cli_get_type ())
#define IPIPE_CLI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IPIPE_CLI, IpipeCli))
#define IPIPE_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IPIPE_CLI, IpipeCliClass))
#define IS_IPIPE_CLI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IPIPE_CLI))
#define IS_IPIPE_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IPIPE_CLI))
#define IPIPE_CLI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IPIPE_CLI, IpipeCliClass))

typedef struct _IpipeCli IpipeCli;
typedef struct _IpipeCliClass IpipeCliClass;

#define TYPE_CLI_MT9P031 (cli_mt9p031_get_type ())
#define CLI_MT9P031(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CLI_MT9P031, cli_mt9p031))
#define CLI_MT9P031_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CLI_MT9P031, cli_mt9p031Class))
#define IS_CLI_MT9P031(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CLI_MT9P031))
#define IS_CLI_MT9P031_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CLI_MT9P031))
#define CLI_MT9P031_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CLI_MT9P031, cli_mt9p031Class))

typedef struct _cli_mt9p031 cli_mt9p031;
typedef struct _cli_mt9p031Class cli_mt9p031Class;
typedef struct _cli_mt9p031Private cli_mt9p031Private;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _IpipeCliPrivate IpipeCliPrivate;

#define TYPE_COMMAND_MANAGER (command_manager_get_type ())
#define COMMAND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMMAND_MANAGER, CommandManager))
#define COMMAND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMMAND_MANAGER, CommandManagerClass))
#define IS_COMMAND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMMAND_MANAGER))
#define IS_COMMAND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMMAND_MANAGER))
#define COMMAND_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMMAND_MANAGER, CommandManagerClass))

typedef struct _CommandManager CommandManager;
typedef struct _CommandManagerClass CommandManagerClass;

struct _Imt9p031Iface {
	GTypeInterface parent_iface;
	gint (*set_sensor_gain) (Imt9p031* self, gdouble r_gain, gdouble g_gain, gdouble b_gain, GError** error);
	gint (*get_sensor_gain) (Imt9p031* self, GError** error);
	gint (*sensor_flip_vertically) (Imt9p031* self, const gchar* state, GError** error);
	gint (*sensor_flip_horizontally) (Imt9p031* self, const gchar* state, GError** error);
	gint (*get_exposure_time) (Imt9p031* self, GError** error);
	gint (*set_exposure_time) (Imt9p031* self, gint _exp_time, GError** error);
};

struct _AbstcCliRegister {
	GObject parent_instance;
	AbstcCliRegisterPrivate * priv;
};

struct _AbstcCliRegisterClass {
	GObjectClass parent_class;
	void (*registration) (AbstcCliRegister* self, IpipeCli* cli, GError** error);
};

struct _cli_mt9p031 {
	AbstcCliRegister parent_instance;
	cli_mt9p031Private * priv;
	Imt9p031* sensor;
};

struct _cli_mt9p031Class {
	AbstcCliRegisterClass parent_class;
};

struct _IpipeCli {
	GObject parent_instance;
	IpipeCliPrivate * priv;
	CommandManager* cmd;
};

struct _IpipeCliClass {
	GObjectClass parent_class;
};

typedef gint (*IpipeCommandCmdFunc) (gchar** s, int s_length1, void* user_data);

static gpointer cli_mt9p031_parent_class = NULL;
static gboolean cli_mt9p031__debug;
static gboolean cli_mt9p031__debug = FALSE;

GType imt9p031_proxy_get_type (void) G_GNUC_CONST;
guint imt9p031_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType imt9p031_get_type (void) G_GNUC_CONST;
gint imt9p031_set_sensor_gain (Imt9p031* self, gdouble r_gain, gdouble g_gain, gdouble b_gain, GError** error);
gint imt9p031_get_sensor_gain (Imt9p031* self, GError** error);
gint imt9p031_sensor_flip_vertically (Imt9p031* self, const gchar* state, GError** error);
gint imt9p031_sensor_flip_horizontally (Imt9p031* self, const gchar* state, GError** error);
gint imt9p031_get_exposure_time (Imt9p031* self, GError** error);
gint imt9p031_set_exposure_time (Imt9p031* self, gint _exp_time, GError** error);
static void imt9p031_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static gint imt9p031_proxy_set_sensor_gain (Imt9p031* self, gdouble r_gain, gdouble g_gain, gdouble b_gain, GError** error);
static gint imt9p031_proxy_get_sensor_gain (Imt9p031* self, GError** error);
static gint imt9p031_proxy_sensor_flip_vertically (Imt9p031* self, const gchar* state, GError** error);
static gint imt9p031_proxy_sensor_flip_horizontally (Imt9p031* self, const gchar* state, GError** error);
static gint imt9p031_proxy_get_exposure_time (Imt9p031* self, GError** error);
static gint imt9p031_proxy_set_exposure_time (Imt9p031* self, gint _exp_time, GError** error);
static void imt9p031_proxy_imt9p031_interface_init (Imt9p031Iface* iface);
static void _dbus_imt9p031_set_sensor_gain (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_imt9p031_get_sensor_gain (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_imt9p031_sensor_flip_vertically (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_imt9p031_sensor_flip_horizontally (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_imt9p031_get_exposure_time (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_imt9p031_set_exposure_time (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void imt9p031_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* imt9p031_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean imt9p031_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _imt9p031_unregister_object (gpointer user_data);
GType abstc_cli_register_get_type (void) G_GNUC_CONST;
GType ipipe_cli_get_type (void) G_GNUC_CONST;
GType cli_mt9p031_get_type (void) G_GNUC_CONST;
enum  {
	CLI_MT9P031_DUMMY_PROPERTY
};
cli_mt9p031* cli_mt9p031_new (gboolean debug);
cli_mt9p031* cli_mt9p031_construct (GType object_type, gboolean debug);
AbstcCliRegister* abstc_cli_register_construct (GType object_type);
gint cli_mt9p031_cmd_set_sensor_gain (cli_mt9p031* self, gchar** args, int args_length1);
gint cli_mt9p031_cmd_get_sensor_gain (cli_mt9p031* self, gchar** args, int args_length1);
gint cli_mt9p031_cmd_flip_vertically (cli_mt9p031* self, gchar** args, int args_length1);
gint cli_mt9p031_cmd_flip_horizontally (cli_mt9p031* self, gchar** args, int args_length1);
gint cli_mt9p031_cmd_set_exposure_time (cli_mt9p031* self, gchar** args, int args_length1);
gint cli_mt9p031_cmd_get_exposure_time (cli_mt9p031* self, gchar** args, int args_length1);
static void cli_mt9p031_real_registration (AbstcCliRegister* base, IpipeCli* cli, GError** error);
GType command_manager_get_type (void) G_GNUC_CONST;
void command_manager_new_command (CommandManager* self, const gchar* _name, IpipeCommandCmdFunc _cmdfunc, void* _cmdfunc_target, const gchar* _usage, const gchar* _doc, const gchar* _args);
static gint _cli_mt9p031_cmd_flip_vertically_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_mt9p031_cmd_flip_horizontally_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_mt9p031_cmd_set_exposure_time_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_mt9p031_cmd_get_exposure_time_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_mt9p031_cmd_set_sensor_gain_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static gint _cli_mt9p031_cmd_get_sensor_gain_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self);
static void cli_mt9p031_finalize (GObject* obj);

static const GDBusArgInfo _imt9p031_dbus_arg_info_set_sensor_gain_r_gain = {-1, "r_gain", "d"};
static const GDBusArgInfo _imt9p031_dbus_arg_info_set_sensor_gain_g_gain = {-1, "g_gain", "d"};
static const GDBusArgInfo _imt9p031_dbus_arg_info_set_sensor_gain_b_gain = {-1, "b_gain", "d"};
static const GDBusArgInfo _imt9p031_dbus_arg_info_set_sensor_gain_result = {-1, "result", "i"};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_set_sensor_gain_in[] = {&_imt9p031_dbus_arg_info_set_sensor_gain_r_gain, &_imt9p031_dbus_arg_info_set_sensor_gain_g_gain, &_imt9p031_dbus_arg_info_set_sensor_gain_b_gain, NULL};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_set_sensor_gain_out[] = {&_imt9p031_dbus_arg_info_set_sensor_gain_result, NULL};
static const GDBusMethodInfo _imt9p031_dbus_method_info_set_sensor_gain = {-1, "SetSensorGain", (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_set_sensor_gain_in), (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_set_sensor_gain_out)};
static const GDBusArgInfo _imt9p031_dbus_arg_info_get_sensor_gain_result = {-1, "result", "i"};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_get_sensor_gain_in[] = {NULL};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_get_sensor_gain_out[] = {&_imt9p031_dbus_arg_info_get_sensor_gain_result, NULL};
static const GDBusMethodInfo _imt9p031_dbus_method_info_get_sensor_gain = {-1, "GetSensorGain", (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_get_sensor_gain_in), (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_get_sensor_gain_out)};
static const GDBusArgInfo _imt9p031_dbus_arg_info_sensor_flip_vertically_state = {-1, "state", "s"};
static const GDBusArgInfo _imt9p031_dbus_arg_info_sensor_flip_vertically_result = {-1, "result", "i"};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_sensor_flip_vertically_in[] = {&_imt9p031_dbus_arg_info_sensor_flip_vertically_state, NULL};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_sensor_flip_vertically_out[] = {&_imt9p031_dbus_arg_info_sensor_flip_vertically_result, NULL};
static const GDBusMethodInfo _imt9p031_dbus_method_info_sensor_flip_vertically = {-1, "SensorFlipVertically", (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_sensor_flip_vertically_in), (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_sensor_flip_vertically_out)};
static const GDBusArgInfo _imt9p031_dbus_arg_info_sensor_flip_horizontally_state = {-1, "state", "s"};
static const GDBusArgInfo _imt9p031_dbus_arg_info_sensor_flip_horizontally_result = {-1, "result", "i"};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_sensor_flip_horizontally_in[] = {&_imt9p031_dbus_arg_info_sensor_flip_horizontally_state, NULL};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_sensor_flip_horizontally_out[] = {&_imt9p031_dbus_arg_info_sensor_flip_horizontally_result, NULL};
static const GDBusMethodInfo _imt9p031_dbus_method_info_sensor_flip_horizontally = {-1, "SensorFlipHorizontally", (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_sensor_flip_horizontally_in), (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_sensor_flip_horizontally_out)};
static const GDBusArgInfo _imt9p031_dbus_arg_info_get_exposure_time_result = {-1, "result", "i"};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_get_exposure_time_in[] = {NULL};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_get_exposure_time_out[] = {&_imt9p031_dbus_arg_info_get_exposure_time_result, NULL};
static const GDBusMethodInfo _imt9p031_dbus_method_info_get_exposure_time = {-1, "GetExposureTime", (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_get_exposure_time_in), (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_get_exposure_time_out)};
static const GDBusArgInfo _imt9p031_dbus_arg_info_set_exposure_time__exp_time = {-1, "_exp_time", "i"};
static const GDBusArgInfo _imt9p031_dbus_arg_info_set_exposure_time_result = {-1, "result", "i"};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_set_exposure_time_in[] = {&_imt9p031_dbus_arg_info_set_exposure_time__exp_time, NULL};
static const GDBusArgInfo * const _imt9p031_dbus_arg_info_set_exposure_time_out[] = {&_imt9p031_dbus_arg_info_set_exposure_time_result, NULL};
static const GDBusMethodInfo _imt9p031_dbus_method_info_set_exposure_time = {-1, "SetExposureTime", (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_set_exposure_time_in), (GDBusArgInfo **) (&_imt9p031_dbus_arg_info_set_exposure_time_out)};
static const GDBusMethodInfo * const _imt9p031_dbus_method_info[] = {&_imt9p031_dbus_method_info_set_sensor_gain, &_imt9p031_dbus_method_info_get_sensor_gain, &_imt9p031_dbus_method_info_sensor_flip_vertically, &_imt9p031_dbus_method_info_sensor_flip_horizontally, &_imt9p031_dbus_method_info_get_exposure_time, &_imt9p031_dbus_method_info_set_exposure_time, NULL};
static const GDBusSignalInfo * const _imt9p031_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _imt9p031_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _imt9p031_dbus_interface_info = {-1, "com.ridgerun.mt9p031Interface", (GDBusMethodInfo **) (&_imt9p031_dbus_method_info), (GDBusSignalInfo **) (&_imt9p031_dbus_signal_info), (GDBusPropertyInfo **) (&_imt9p031_dbus_property_info)};
static const GDBusInterfaceVTable _imt9p031_dbus_interface_vtable = {imt9p031_dbus_interface_method_call, imt9p031_dbus_interface_get_property, imt9p031_dbus_interface_set_property};

gint imt9p031_set_sensor_gain (Imt9p031* self, gdouble r_gain, gdouble g_gain, gdouble b_gain, GError** error) {
	return IMT9P031_GET_INTERFACE (self)->set_sensor_gain (self, r_gain, g_gain, b_gain, error);
}


gint imt9p031_get_sensor_gain (Imt9p031* self, GError** error) {
	return IMT9P031_GET_INTERFACE (self)->get_sensor_gain (self, error);
}


gint imt9p031_sensor_flip_vertically (Imt9p031* self, const gchar* state, GError** error) {
	return IMT9P031_GET_INTERFACE (self)->sensor_flip_vertically (self, state, error);
}


gint imt9p031_sensor_flip_horizontally (Imt9p031* self, const gchar* state, GError** error) {
	return IMT9P031_GET_INTERFACE (self)->sensor_flip_horizontally (self, state, error);
}


gint imt9p031_get_exposure_time (Imt9p031* self, GError** error) {
	return IMT9P031_GET_INTERFACE (self)->get_exposure_time (self, error);
}


gint imt9p031_set_exposure_time (Imt9p031* self, gint _exp_time, GError** error) {
	return IMT9P031_GET_INTERFACE (self)->set_exposure_time (self, _exp_time, error);
}


static void imt9p031_base_init (Imt9p031Iface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType imt9p031_get_type (void) {
	static volatile gsize imt9p031_type_id__volatile = 0;
	if (g_once_init_enter (&imt9p031_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Imt9p031Iface), (GBaseInitFunc) imt9p031_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType imt9p031_type_id;
		imt9p031_type_id = g_type_register_static (G_TYPE_INTERFACE, "Imt9p031", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (imt9p031_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (imt9p031_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) imt9p031_proxy_get_type);
		g_type_set_qdata (imt9p031_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "com.ridgerun.mt9p031Interface");
		g_type_set_qdata (imt9p031_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) imt9p031_register_object);
		g_once_init_leave (&imt9p031_type_id__volatile, imt9p031_type_id);
	}
	return imt9p031_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (Imt9p031Proxy, imt9p031_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_IMT9P031, imt9p031_proxy_imt9p031_interface_init) )
static void imt9p031_proxy_class_init (Imt9p031ProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = imt9p031_proxy_g_signal;
}


static void imt9p031_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void imt9p031_proxy_init (Imt9p031Proxy* self) {
}


static gint imt9p031_proxy_set_sensor_gain (Imt9p031* self, gdouble r_gain, gdouble g_gain, gdouble b_gain, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp33_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.mt9p031Interface", "SetSensorGain");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (r_gain));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (g_gain));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (b_gain));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp33_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp33_);
	g_variant_unref (_tmp33_);
	g_object_unref (_reply_message);
	return _result;
}


static gint imt9p031_proxy_get_sensor_gain (Imt9p031* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp34_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.mt9p031Interface", "GetSensorGain");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp34_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp34_);
	g_variant_unref (_tmp34_);
	g_object_unref (_reply_message);
	return _result;
}


static gint imt9p031_proxy_sensor_flip_vertically (Imt9p031* self, const gchar* state, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp35_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.mt9p031Interface", "SensorFlipVertically");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (state));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp35_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp35_);
	g_variant_unref (_tmp35_);
	g_object_unref (_reply_message);
	return _result;
}


static gint imt9p031_proxy_sensor_flip_horizontally (Imt9p031* self, const gchar* state, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp36_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.mt9p031Interface", "SensorFlipHorizontally");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (state));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp36_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp36_);
	g_variant_unref (_tmp36_);
	g_object_unref (_reply_message);
	return _result;
}


static gint imt9p031_proxy_get_exposure_time (Imt9p031* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp37_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.mt9p031Interface", "GetExposureTime");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp37_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp37_);
	g_variant_unref (_tmp37_);
	g_object_unref (_reply_message);
	return _result;
}


static gint imt9p031_proxy_set_exposure_time (Imt9p031* self, gint _exp_time, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gint _result;
	GVariant* _tmp38_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.ridgerun.mt9p031Interface", "SetExposureTime");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (_exp_time));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return 0;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return 0;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp38_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_int32 (_tmp38_);
	g_variant_unref (_tmp38_);
	g_object_unref (_reply_message);
	return _result;
}


static void imt9p031_proxy_imt9p031_interface_init (Imt9p031Iface* iface) {
	iface->set_sensor_gain = imt9p031_proxy_set_sensor_gain;
	iface->get_sensor_gain = imt9p031_proxy_get_sensor_gain;
	iface->sensor_flip_vertically = imt9p031_proxy_sensor_flip_vertically;
	iface->sensor_flip_horizontally = imt9p031_proxy_sensor_flip_horizontally;
	iface->get_exposure_time = imt9p031_proxy_get_exposure_time;
	iface->set_exposure_time = imt9p031_proxy_set_exposure_time;
}


static void _dbus_imt9p031_set_sensor_gain (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gdouble r_gain = 0.0;
	GVariant* _tmp39_;
	gdouble g_gain = 0.0;
	GVariant* _tmp40_;
	gdouble b_gain = 0.0;
	GVariant* _tmp41_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp39_ = g_variant_iter_next_value (&_arguments_iter);
	r_gain = g_variant_get_double (_tmp39_);
	g_variant_unref (_tmp39_);
	_tmp40_ = g_variant_iter_next_value (&_arguments_iter);
	g_gain = g_variant_get_double (_tmp40_);
	g_variant_unref (_tmp40_);
	_tmp41_ = g_variant_iter_next_value (&_arguments_iter);
	b_gain = g_variant_get_double (_tmp41_);
	g_variant_unref (_tmp41_);
	result = imt9p031_set_sensor_gain (self, r_gain, g_gain, b_gain, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_imt9p031_get_sensor_gain (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = imt9p031_get_sensor_gain (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_imt9p031_sensor_flip_vertically (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* state = NULL;
	GVariant* _tmp42_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp42_ = g_variant_iter_next_value (&_arguments_iter);
	state = g_variant_dup_string (_tmp42_, NULL);
	g_variant_unref (_tmp42_);
	result = imt9p031_sensor_flip_vertically (self, state, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (state);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_imt9p031_sensor_flip_horizontally (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* state = NULL;
	GVariant* _tmp43_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp43_ = g_variant_iter_next_value (&_arguments_iter);
	state = g_variant_dup_string (_tmp43_, NULL);
	g_variant_unref (_tmp43_);
	result = imt9p031_sensor_flip_horizontally (self, state, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (state);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_imt9p031_get_exposure_time (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = imt9p031_get_exposure_time (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_imt9p031_set_exposure_time (Imt9p031* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gint _exp_time = 0;
	GVariant* _tmp44_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp44_ = g_variant_iter_next_value (&_arguments_iter);
	_exp_time = g_variant_get_int32 (_tmp44_);
	g_variant_unref (_tmp44_);
	result = imt9p031_set_exposure_time (self, _exp_time, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void imt9p031_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "SetSensorGain") == 0) {
		_dbus_imt9p031_set_sensor_gain (object, parameters, invocation);
	} else if (strcmp (method_name, "GetSensorGain") == 0) {
		_dbus_imt9p031_get_sensor_gain (object, parameters, invocation);
	} else if (strcmp (method_name, "SensorFlipVertically") == 0) {
		_dbus_imt9p031_sensor_flip_vertically (object, parameters, invocation);
	} else if (strcmp (method_name, "SensorFlipHorizontally") == 0) {
		_dbus_imt9p031_sensor_flip_horizontally (object, parameters, invocation);
	} else if (strcmp (method_name, "GetExposureTime") == 0) {
		_dbus_imt9p031_get_exposure_time (object, parameters, invocation);
	} else if (strcmp (method_name, "SetExposureTime") == 0) {
		_dbus_imt9p031_set_exposure_time (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* imt9p031_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean imt9p031_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint imt9p031_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_imt9p031_dbus_interface_info), &_imt9p031_dbus_interface_vtable, data, _imt9p031_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _imt9p031_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


cli_mt9p031* cli_mt9p031_construct (GType object_type, gboolean debug) {
	cli_mt9p031 * self = NULL;
	self = (cli_mt9p031*) abstc_cli_register_construct (object_type);
	cli_mt9p031__debug = debug;
	return self;
}


cli_mt9p031* cli_mt9p031_new (gboolean debug) {
	return cli_mt9p031_construct (TYPE_CLI_MT9P031, debug);
}


static gdouble double_parse (const gchar* str) {
	gdouble result = 0.0;
	gdouble _tmp0_;
	g_return_val_if_fail (str != NULL, 0.0);
	_tmp0_ = g_ascii_strtod (str, NULL);
	result = _tmp0_;
	return result;
}


gint cli_mt9p031_cmd_set_sensor_gain (cli_mt9p031* self, gchar** args, int args_length1) {
	gint result = 0;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gdouble _tmp2_;
	gdouble red;
	gdouble _tmp3_;
	gdouble green;
	gdouble _tmp4_;
	gdouble blue;
	gint _tmp5_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	if (args[1] == NULL) {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = args[2] == NULL;
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = args[3] == NULL;
	}
	if (_tmp0_) {
		fprintf (stdout, "Error:\nMissing argument.Execute:'help <command>'\n");
		result = -1;
		return result;
	}
	_tmp2_ = double_parse (args[1]);
	red = _tmp2_;
	_tmp3_ = double_parse (args[2]);
	green = _tmp3_;
	_tmp4_ = double_parse (args[3]);
	blue = _tmp4_;
	_tmp5_ = imt9p031_set_sensor_gain (self->sensor, red, green, blue, &_inner_error_);
	ret = _tmp5_;
	if (_inner_error_ != NULL) {
		goto __catch15_g_error;
	}
	if (ret != 0) {
		fprintf (stderr, "Error:\n Failed to set sensor gain\n");
		result = -1;
		return result;
	} else {
		if (cli_mt9p031__debug) {
			fprintf (stdout, "Ok.Set sensor gain\n");
		}
		result = 0;
		return result;
	}
	goto __finally15;
	__catch15_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally15:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


/** 
     * Cmd Get sensor gain
     * Use the get_sensor_gain function to obtain the RGB sensor gains 
     * and print them
     */
gint cli_mt9p031_cmd_get_sensor_gain (cli_mt9p031* self, gchar** args, int args_length1) {
	gint result = 0;
	gint _tmp0_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = imt9p031_get_sensor_gain (self->sensor, &_inner_error_);
	ret = _tmp0_;
	if (_inner_error_ != NULL) {
		goto __catch16_g_error;
	}
	if (ret != 0) {
		fprintf (stderr, "Error:\n Failed to get sensor gain\n");
		result = -1;
		return result;
	} else {
		if (cli_mt9p031__debug) {
			fprintf (stdout, "Ok.Get sensor gain\n");
		}
		result = 0;
		return result;
	}
	goto __finally16;
	__catch16_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally16:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


gint cli_mt9p031_cmd_flip_vertically (cli_mt9p031* self, gchar** args, int args_length1) {
	gint result = 0;
	gint _tmp0_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	if (args[1] == NULL) {
		fprintf (stdout, "Error:\nMissing argument.Execute:'help <command>'\n");
		result = -1;
		return result;
	}
	_tmp0_ = imt9p031_sensor_flip_vertically (self->sensor, args[1], &_inner_error_);
	ret = _tmp0_;
	if (_inner_error_ != NULL) {
		goto __catch17_g_error;
	}
	if (ret != 0) {
		fprintf (stderr, "Error:\n Failed to set vertical flip\n");
		result = -1;
		return result;
	} else {
		if (cli_mt9p031__debug) {
			fprintf (stdout, "Ok.Flip vertical\n");
		}
		result = 0;
		return result;
	}
	goto __finally17;
	__catch17_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally17:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


gint cli_mt9p031_cmd_flip_horizontally (cli_mt9p031* self, gchar** args, int args_length1) {
	gint result = 0;
	gint _tmp0_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	if (args[1] == NULL) {
		fprintf (stdout, "Error:\nMissing argument.Execute:'help <command>'\n");
		result = -1;
		return result;
	}
	_tmp0_ = imt9p031_sensor_flip_horizontally (self->sensor, args[1], &_inner_error_);
	ret = _tmp0_;
	if (_inner_error_ != NULL) {
		goto __catch18_g_error;
	}
	if (ret != 0) {
		fprintf (stderr, "Error:\n Failed to set horizontal flip\n");
		result = -1;
		return result;
	} else {
		if (cli_mt9p031__debug) {
			fprintf (stdout, "Ok.Flip horizontal\n");
		}
		result = 0;
		return result;
	}
	goto __finally18;
	__catch18_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally18:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


gint cli_mt9p031_cmd_set_exposure_time (cli_mt9p031* self, gchar** args, int args_length1) {
	gint result = 0;
	gint _tmp0_;
	gint time;
	gint _tmp1_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	if (args[1] == NULL) {
		fprintf (stdout, "Error:\nMissing argument.Execute:'help <command>'\n");
		result = -1;
		return result;
	}
	_tmp0_ = atoi (args[1]);
	time = _tmp0_;
	_tmp1_ = imt9p031_set_exposure_time (self->sensor, time, &_inner_error_);
	ret = _tmp1_;
	if (_inner_error_ != NULL) {
		goto __catch19_g_error;
	}
	if (ret != 0) {
		fprintf (stderr, "Error:\n Failed to set exposure time\n");
		result = -1;
		return result;
	} else {
		if (cli_mt9p031__debug) {
			fprintf (stdout, "Ok.Set exposure time\n");
		}
		result = 0;
		return result;
	}
	goto __finally19;
	__catch19_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally19:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


gint cli_mt9p031_cmd_get_exposure_time (cli_mt9p031* self, gchar** args, int args_length1) {
	gint result = 0;
	gint _tmp0_;
	gint ret;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = imt9p031_get_exposure_time (self->sensor, &_inner_error_);
	ret = _tmp0_;
	if (_inner_error_ != NULL) {
		goto __catch20_g_error;
	}
	if (ret != 0) {
		fprintf (stderr, "Error:\n Failed to set exposure time\n");
		result = -1;
		return result;
	} else {
		if (cli_mt9p031__debug) {
			fprintf (stdout, "Ok.Get exposure time\n");
		}
		result = 0;
		return result;
	}
	goto __finally20;
	__catch20_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		fprintf (stderr, "Fail to execute command:%s\n", e->message);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally20:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


static gint _cli_mt9p031_cmd_flip_vertically_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_mt9p031_cmd_flip_vertically (self, s, s_length1);
	return result;
}


static gint _cli_mt9p031_cmd_flip_horizontally_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_mt9p031_cmd_flip_horizontally (self, s, s_length1);
	return result;
}


static gint _cli_mt9p031_cmd_set_exposure_time_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_mt9p031_cmd_set_exposure_time (self, s, s_length1);
	return result;
}


static gint _cli_mt9p031_cmd_get_exposure_time_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_mt9p031_cmd_get_exposure_time (self, s, s_length1);
	return result;
}


static gint _cli_mt9p031_cmd_set_sensor_gain_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_mt9p031_cmd_set_sensor_gain (self, s, s_length1);
	return result;
}


static gint _cli_mt9p031_cmd_get_sensor_gain_ipipe_command_cmd_func (gchar** s, int s_length1, gpointer self) {
	gint result;
	result = cli_mt9p031_cmd_get_sensor_gain (self, s, s_length1);
	return result;
}


static void cli_mt9p031_real_registration (AbstcCliRegister* base, IpipeCli* cli, GError** error) {
	cli_mt9p031 * self;
	Imt9p031* _tmp0_ = NULL;
	Imt9p031* _tmp1_;
	GError * _inner_error_ = NULL;
	self = (cli_mt9p031*) base;
	g_return_if_fail (cli != NULL);
	command_manager_new_command (cli->cmd, "flip-vertical", _cli_mt9p031_cmd_flip_vertically_ipipe_command_cmd_func, self, "fip-vertical <state>", "Flips the image vertically(on the sensor)", "state indicates the " "status of the vertical flip.\n\t The options are \"ON\" or " " \"OFF\"");
	command_manager_new_command (cli->cmd, "flip-horizontal", _cli_mt9p031_cmd_flip_horizontally_ipipe_command_cmd_func, self, "flip-horizontal" "<state>", "Flips the image horizontally (on the sensor)", "state indicates the status of the horizontal flip." "\n\t The options are \"ON\" or \"OFF\"");
	command_manager_new_command (cli->cmd, "set-exposure", _cli_mt9p031_cmd_set_exposure_time_ipipe_command_cmd_func, self, "set-exposure <T[us]>", "Sets the effective shutter time  of the sensor for the light " "integration", "T: effective shutter time in micro-seconds");
	command_manager_new_command (cli->cmd, "get-exposure", _cli_mt9p031_cmd_get_exposure_time_ipipe_command_cmd_func, self, "get-exposure", "Gets the exposure time of the sensor in us", "");
	command_manager_new_command (cli->cmd, "set-sensor-gain", _cli_mt9p031_cmd_set_sensor_gain_ipipe_command_cmd_func, self, "set-sensor-gain <R> <G> <B>", "Sets red(R), green(G) and blue(B) gain directly on the sensor", "\n\tEach gain component can range from 0 to 128 in steps of " "\n\t\t0.125 if gain between 1 and 4\n\t\t0.250 if gain " "between 4.25 and 8\n\t\t1.000 if gain betwewn 8 and 128" "\n\tR: red gain\n\tG: green gain\n\tB: blue gain\n");
	command_manager_new_command (cli->cmd, "get-sensor-gain", _cli_mt9p031_cmd_get_sensor_gain_ipipe_command_cmd_func, self, "get-sensor-gain", "Gets sensor red(R), green(G) and blue(B)", "");
	_tmp0_ = g_initable_new (TYPE_IMT9P031_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "com.ridgerun.ipiped", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", "/com/ridgerun/ipiped/ipipe", "g-interface-name", "com.ridgerun.mt9p031Interface", NULL);
	_tmp1_ = (Imt9p031*) _tmp0_;
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_IO_ERROR) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_g_object_unref0 (self->sensor);
	self->sensor = _tmp1_;
	return;
}


static void cli_mt9p031_class_init (cli_mt9p031Class * klass) {
	cli_mt9p031_parent_class = g_type_class_peek_parent (klass);
	ABSTC_CLI_REGISTER_CLASS (klass)->registration = cli_mt9p031_real_registration;
	G_OBJECT_CLASS (klass)->finalize = cli_mt9p031_finalize;
}


static void cli_mt9p031_instance_init (cli_mt9p031 * self) {
}


static void cli_mt9p031_finalize (GObject* obj) {
	cli_mt9p031 * self;
	self = CLI_MT9P031 (obj);
	_g_object_unref0 (self->sensor);
	G_OBJECT_CLASS (cli_mt9p031_parent_class)->finalize (obj);
}


GType cli_mt9p031_get_type (void) {
	static volatile gsize cli_mt9p031_type_id__volatile = 0;
	if (g_once_init_enter (&cli_mt9p031_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (cli_mt9p031Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cli_mt9p031_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (cli_mt9p031), 0, (GInstanceInitFunc) cli_mt9p031_instance_init, NULL };
		GType cli_mt9p031_type_id;
		cli_mt9p031_type_id = g_type_register_static (TYPE_ABSTC_CLI_REGISTER, "cli_mt9p031", &g_define_type_info, 0);
		g_once_init_leave (&cli_mt9p031_type_id__volatile, cli_mt9p031_type_id);
	}
	return cli_mt9p031_type_id__volatile;
}



